version: '3.7'
services:
  db:
    image: mysql
    volumes:
    - ~/docker/volumes/mysql:/var/lib/mysql/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rent
  app:
    build: .
    ports:
    - 8080:8080
